### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by hdcos** [szktty/bran#2]
Hi! :) I am pretty interested in this project. Is it dead or alive?

I am using elixir right now but the more I use it the more I want to use static type checking in my compilation phase.

Is bran compatible with elixir? Can I use elixir libraries from bran?
Would it be extremely difficult to build a typed superset of the elixir language (sort of typescript but for elixir)?

**Comment by szktty** [comment]
@hdcos Hi. This project is dead. I don't have enough time to develop and it is difficult to design type inference satisfies many Erlang users. I think that it is needed to create a new rule for typing statically with any restrictions on dynamic typing. But the restrictions can satisfy only part of users.

Elixir can call Erlang functions, can't it? Generated codes by Bran, which is a translator to Erlang, may be called from Elixir (sorry, I have not tried it).

**Comment by dmilith** [comment]
SAD Panda :(
